#!/usr/bin/env ansible-playbook

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
# root_volume_aggregate currently not supported with REST
      use_rest:       Always
  vars_files:
    - global_nas.vars
  collections:
    - netapp.ontap



  tasks:
  - name: Info
    netapp.ontap.na_ontap_info:
      hostname: "cluster1"
      username: "admin"
      password: "Parola123#"
    register: ontap_info
  - debug:
        msg: "{{ ontap_info.ontap_info }}"

